import { IDataOfNewcomers } from 'src/components/SdNewcomersTable/SdNewcomersTable.tsx';

export const mockData: IDataOfNewcomers[] = [
  {
    id: '1',
    domainName: 'test_name',
    nameEn: 'Ivan Ivaniv',
    nameRu: 'Иван Иванов Сергеевич',
    email: 'ivan.ivanov@company.com',
    request: 'NEWCOMERS-1',
    startDate: '22.12.2023',
  },
  {
    id: '2',
    domainName: 'test_name2',
    nameEn: 'Ivan2 Ivaniv',
    nameRu: 'Иван2 Иванов Сергеевич',
    email: 'ivan2.ivanov@company.com',
    request: 'NEWCOMERS-2',
    startDate: '12.12.2023',
  },
  {
    id: '3',
    domainName: 'test3_name',
    nameEn: 'Ivan3 Ivaniv3',
    nameRu: 'Иван3 Иванов Сергеевич3',
    email: 'ivan3.ivanov3@company.com',
    request: 'NEWCOMERS-3',
    startDate: '23.12.2023',
  },
  {
    id: '4',
    domainName: 'test4_name',
    nameEn: 'Ivan4 4',
    nameRu: 'Иван4 Иванов Сергеевич',
    email: 'ivan4.4ivanov@company.com',
    request: 'NEWCOMERS-4',
    startDate: '24.12.2023',
  },
  {
    id: '5',
    domainName: 'test5_name',
    nameEn: 'Ivan5 Ivaniv5',
    nameRu: 'Иван5Иванов5 Сергеевич',
    email: 'ivan5.ivanov@company.com',
    request: 'NEWCOMERS-5',
    startDate: '22.12.2023',
  },
  {
    id: '16',
    domainName: 'test6_name',
    nameEn: 'Ivan6 Ivaniv6',
    nameRu: 'Иван6 Иванов6 Сергеевич',
    email: 'ivan6.6vanov@company.com',
    request: 'NEWCOMERS-6',
    startDate: '26.12.2023',
  },
  {
    id: '7',
    domainName: 'test7_name7',
    nameEn: 'Ivan7 Ivaniv',
    nameRu: 'Иван7 Иванов Сергеевич',
    email: 'ivan7.ivanov@company.com',
    request: 'NEWCOMERS-7',
    startDate: '27.12.2023',
  },
  {
    id: '8',
    domainName: 'test8_name8',
    nameEn: 'Ivan8 Ivaniv8',
    nameRu: 'Иван8 Иванов8 Сергеевич',
    email: 'ivan8.ivanov@company.com',
    request: 'NEWCOMERS-8',
    startDate: '28.12.2023',
  },
  {
    id: '9',
    domainName: '9test_9name',
    nameEn: 'Iv9an Ivani9v',
    nameRu: 'Ива9н Ив9анов Сергеевич',
    email: 'ivan9.iva9nov@company.com',
    request: 'NEWCOMERS-9',
    startDate: '29.12.2023',
  },
  {
    id: '10',
    domainName: 'te0st_na0me',
    nameEn: 'Iv0an Iva0niv',
    nameRu: 'Ив0ан Иванов Сер0гее0вич',
    email: 'ivan.0iva0nov@comp0any.com',
    request: 'NEWCOMERS-10',
    startDate: '30.12.2023',
  },
  {
    id: '1',
    domainName: 'test_name',
    nameEn: 'Ivan Ivaniv',
    nameRu: 'Иван Иванов Сергеевич',
    email: 'ivan.ivanov@company.com',
    request: 'NEWCOMERS-1',
    startDate: '22.12.2023',
  },
  {
    id: '2',
    domainName: 'test_name2',
    nameEn: 'Ivan2 Ivaniv',
    nameRu: 'Иван2 Иванов Сергеевич',
    email: 'ivan2.ivanov@company.com',
    request: 'NEWCOMERS-2',
    startDate: '12.12.2023',
  },
  {
    id: '3',
    domainName: 'test3_name',
    nameEn: 'Ivan3 Ivaniv3',
    nameRu: 'Иван3 Иванов Сергеевич3',
    email: 'ivan3.ivanov3@company.com',
    request: 'NEWCOMERS-3',
    startDate: '23.12.2023',
  },
  {
    id: '4',
    domainName: 'test4_name',
    nameEn: 'Ivan4 4',
    nameRu: 'Иван4 Иванов Сергеевич',
    email: 'ivan4.4ivanov@company.com',
    request: 'NEWCOMERS-4',
    startDate: '24.12.2023',
  },
  {
    id: '5',
    domainName: 'test5_name',
    nameEn: 'Ivan5 Ivaniv5',
    nameRu: 'Иван5Иванов5 Сергеевич',
    email: 'ivan5.ivanov@company.com',
    request: 'NEWCOMERS-5',
    startDate: '22.12.2023',
  },
  {
    id: '16',
    domainName: 'test6_name',
    nameEn: 'Ivan6 Ivaniv6',
    nameRu: 'Иван6 Иванов6 Сергеевич',
    email: 'ivan6.6vanov@company.com',
    request: 'NEWCOMERS-6',
    startDate: '26.12.2023',
  },
  {
    id: '7',
    domainName: 'test7_name7',
    nameEn: 'Ivan7 Ivaniv',
    nameRu: 'Иван7 Иванов Сергеевич',
    email: 'ivan7.ivanov@company.com',
    request: 'NEWCOMERS-7',
    startDate: '27.12.2023',
  },
  {
    id: '8',
    domainName: 'test8_name8',
    nameEn: 'Ivan8 Ivaniv8',
    nameRu: 'Иван8 Иванов8 Сергеевич',
    email: 'ivan8.ivanov@company.com',
    request: 'NEWCOMERS-8',
    startDate: '28.12.2023',
  },
  {
    id: '9',
    domainName: '9test_9name',
    nameEn: 'Iv9an Ivani9v',
    nameRu: 'Ива9н Ив9анов Сергеевич',
    email: 'ivan9.iva9nov@company.com',
    request: 'NEWCOMERS-9',
    startDate: '29.12.2023',
  },
  {
    id: '10',
    domainName: 'te0st_na0me',
    nameEn: 'Iv0an Iva0niv',
    nameRu: 'Ив0ан Иванов Сер0гее0вич',
    email: 'ivan.0iva0nov@comp0any.com',
    request: 'NEWCOMERS-10',
    startDate: '30.12.2023',
  },
  {
    id: '1',
    domainName: 'test_name',
    nameEn: 'Ivan Ivaniv',
    nameRu: 'Иван Иванов Сергеевич',
    email: 'ivan.ivanov@company.com',
    request: 'NEWCOMERS-1',
    startDate: '22.12.2023',
  },
  {
    id: '2',
    domainName: 'test_name2',
    nameEn: 'Ivan2 Ivaniv',
    nameRu: 'Иван2 Иванов Сергеевич',
    email: 'ivan2.ivanov@company.com',
    request: 'NEWCOMERS-2',
    startDate: '12.12.2023',
  },
  {
    id: '3',
    domainName: 'test3_name',
    nameEn: 'Ivan3 Ivaniv3',
    nameRu: 'Иван3 Иванов Сергеевич3',
    email: 'ivan3.ivanov3@company.com',
    request: 'NEWCOMERS-3',
    startDate: '23.12.2023',
  },
  {
    id: '4',
    domainName: 'test4_name',
    nameEn: 'Ivan4 4',
    nameRu: 'Иван4 Иванов Сергеевич',
    email: 'ivan4.4ivanov@company.com',
    request: 'NEWCOMERS-4',
    startDate: '24.12.2023',
  },
  {
    id: '5',
    domainName: 'test5_name',
    nameEn: 'Ivan5 Ivaniv5',
    nameRu: 'Иван5Иванов5 Сергеевич',
    email: 'ivan5.ivanov@company.com',
    request: 'NEWCOMERS-5',
    startDate: '22.12.2023',
  },
  {
    id: '16',
    domainName: 'test6_name',
    nameEn: 'Ivan6 Ivaniv6',
    nameRu: 'Иван6 Иванов6 Сергеевич',
    email: 'ivan6.6vanov@company.com',
    request: 'NEWCOMERS-6',
    startDate: '26.12.2023',
  },
  {
    id: '7',
    domainName: 'test7_name7',
    nameEn: 'Ivan7 Ivaniv',
    nameRu: 'Иван7 Иванов Сергеевич',
    email: 'ivan7.ivanov@company.com',
    request: 'NEWCOMERS-7',
    startDate: '27.12.2023',
  },
  {
    id: '8',
    domainName: 'test8_name8',
    nameEn: 'Ivan8 Ivaniv8',
    nameRu: 'Иван8 Иванов8 Сергеевич',
    email: 'ivan8.ivanov@company.com',
    request: 'NEWCOMERS-8',
    startDate: '28.12.2023',
  },
  {
    id: '9',
    domainName: '9test_9name',
    nameEn: 'Iv9an Ivani9v',
    nameRu: 'Ива9н Ив9анов Сергеевич',
    email: 'ivan9.iva9nov@company.com',
    request: 'NEWCOMERS-9',
    startDate: '29.12.2023',
  },
  {
    id: '10',
    domainName: 'te0st_na0me',
    nameEn: 'Iv0an Iva0niv',
    nameRu: 'Ив0ан Иванов Сер0гее0вич',
    email: 'ivan.0iva0nov@comp0any.com',
    request: 'NEWCOMERS-10',
    startDate: '30.12.2023',
  },
  {
    id: '1',
    domainName: 'test_name',
    nameEn: 'Ivan Ivaniv',
    nameRu: 'Иван Иванов Сергеевич',
    email: 'ivan.ivanov@company.com',
    request: 'NEWCOMERS-1',
    startDate: '22.12.2023',
  },
  {
    id: '2',
    domainName: 'test_name2',
    nameEn: 'Ivan2 Ivaniv',
    nameRu: 'Иван2 Иванов Сергеевич',
    email: 'ivan2.ivanov@company.com',
    request: 'NEWCOMERS-2',
    startDate: '12.12.2023',
  },
  {
    id: '3',
    domainName: 'test3_name',
    nameEn: 'Ivan3 Ivaniv3',
    nameRu: 'Иван3 Иванов Сергеевич3',
    email: 'ivan3.ivanov3@company.com',
    request: 'NEWCOMERS-3',
    startDate: '23.12.2023',
  },
  {
    id: '4',
    domainName: 'test4_name',
    nameEn: 'Ivan4 4',
    nameRu: 'Иван4 Иванов Сергеевич',
    email: 'ivan4.4ivanov@company.com',
    request: 'NEWCOMERS-4',
    startDate: '24.12.2023',
  },
  {
    id: '5',
    domainName: 'test5_name',
    nameEn: 'Ivan5 Ivaniv5',
    nameRu: 'Иван5Иванов5 Сергеевич',
    email: 'ivan5.ivanov@company.com',
    request: 'NEWCOMERS-5',
    startDate: '22.12.2023',
  },
  {
    id: '16',
    domainName: 'test6_name',
    nameEn: 'Ivan6 Ivaniv6',
    nameRu: 'Иван6 Иванов6 Сергеевич',
    email: 'ivan6.6vanov@company.com',
    request: 'NEWCOMERS-6',
    startDate: '26.12.2023',
  },
  {
    id: '7',
    domainName: 'test7_name7',
    nameEn: 'Ivan7 Ivaniv',
    nameRu: 'Иван7 Иванов Сергеевич',
    email: 'ivan7.ivanov@company.com',
    request: 'NEWCOMERS-7',
    startDate: '27.12.2023',
  },
  {
    id: '8',
    domainName: 'test8_name8',
    nameEn: 'Ivan8 Ivaniv8',
    nameRu: 'Иван8 Иванов8 Сергеевич',
    email: 'ivan8.ivanov@company.com',
    request: 'NEWCOMERS-8',
    startDate: '28.12.2023',
  },
  {
    id: '9',
    domainName: '9test_9name',
    nameEn: 'Iv9an Ivani9v',
    nameRu: 'Ива9н Ив9анов Сергеевич',
    email: 'ivan9.iva9nov@company.com',
    request: 'NEWCOMERS-9',
    startDate: '29.12.2023',
  },
  {
    id: '10',
    domainName: 'te0st_na0me',
    nameEn: 'Iv0an Iva0niv',
    nameRu: 'Ив0ан Иванов Сер0гее0вич',
    email: 'ivan.0iva0nov@comp0any.com',
    request: 'NEWCOMERS-10',
    startDate: '30.12.2023',
  },
  {
    id: '1',
    domainName: 'test_name',
    nameEn: 'Ivan Ivaniv',
    nameRu: 'Иван Иванов Сергеевич',
    email: 'ivan.ivanov@company.com',
    request: 'NEWCOMERS-1',
    startDate: '22.12.2023',
  },
  {
    id: '2',
    domainName: 'test_name2',
    nameEn: 'Ivan2 Ivaniv',
    nameRu: 'Иван2 Иванов Сергеевич',
    email: 'ivan2.ivanov@company.com',
    request: 'NEWCOMERS-2',
    startDate: '12.12.2023',
  },
  {
    id: '3',
    domainName: 'test3_name',
    nameEn: 'Ivan3 Ivaniv3',
    nameRu: 'Иван3 Иванов Сергеевич3',
    email: 'ivan3.ivanov3@company.com',
    request: 'NEWCOMERS-3',
    startDate: '23.12.2023',
  },
  {
    id: '4',
    domainName: 'test4_name',
    nameEn: 'Ivan4 4',
    nameRu: 'Иван4 Иванов Сергеевич',
    email: 'ivan4.4ivanov@company.com',
    request: 'NEWCOMERS-4',
    startDate: '24.12.2023',
  },
  {
    id: '5',
    domainName: 'test5_name',
    nameEn: 'Ivan5 Ivaniv5',
    nameRu: 'Иван5Иванов5 Сергеевич',
    email: 'ivan5.ivanov@company.com',
    request: 'NEWCOMERS-5',
    startDate: '22.12.2023',
  },
  {
    id: '16',
    domainName: 'test6_name',
    nameEn: 'Ivan6 Ivaniv6',
    nameRu: 'Иван6 Иванов6 Сергеевич',
    email: 'ivan6.6vanov@company.com',
    request: 'NEWCOMERS-6',
    startDate: '26.12.2023',
  },
  {
    id: '7',
    domainName: 'test7_name7',
    nameEn: 'Ivan7 Ivaniv',
    nameRu: 'Иван7 Иванов Сергеевич',
    email: 'ivan7.ivanov@company.com',
    request: 'NEWCOMERS-7',
    startDate: '27.12.2023',
  },
  {
    id: '8',
    domainName: 'test8_name8',
    nameEn: 'Ivan8 Ivaniv8',
    nameRu: 'Иван8 Иванов8 Сергеевич',
    email: 'ivan8.ivanov@company.com',
    request: 'NEWCOMERS-8',
    startDate: '28.12.2023',
  },
  {
    id: '9',
    domainName: '9test_9name',
    nameEn: 'Iv9an Ivani9v',
    nameRu: 'Ива9н Ив9анов Сергеевич',
    email: 'ivan9.iva9nov@company.com',
    request: 'NEWCOMERS-9',
    startDate: '29.12.2023',
  },
  {
    id: '10',
    domainName: 'te0st_na0me',
    nameEn: 'Iv0an Iva0niv',
    nameRu: 'Ив0ан Иванов Сер0гее0вич',
    email: 'ivan.0iva0nov@comp0any.com',
    request: 'NEWCOMERS-10',
    startDate: '30.12.2023',
  },
];
