name: Frontend - Deploy on VPS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'www-grimoire/**'

env:
  VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  deployment:

    runs-on: self-hosted
    environment: Production – grimoire

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Settings variables
      working-directory: www-grimoire
      run: |
        touch .env
        echo VITE_BACKEND_URL=$VITE_BACKEND_URL >> .env
        echo SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN >> .env
        echo VITE_NODE_ENV="production" >> .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: www-grimoire
      run: npm install

    - name: Build project
      working-directory: www-grimoire
      run: npm run build

    - name: Delete dist folder
      working-directory: www-grimoire
      run: rm -r /home/bot_cerberus/data/www/grimoire.v-b.tech

    - name: Move dist folder
      working-directory: www-grimoire
      run: mv /home/bot_cerberus/data/www/actions-runner/backend/Grimoire/Grimoire/www-grimoire/dist /home/bot_cerberus/data/www/grimoire.v-b.tech
