name: Frontend - Tests on PR

on:
  push:
    paths:
      - 'www-grimoire/**'
    branches:
      - main
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x,]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./www-grimoire
        run: yarn

      - name: Building
        working-directory: ./www-grimoire
        run: yarn build

      - name: Linting
        working-directory: ./www-grimoire
        run: yarn lint

      - name: Tests
        working-directory: ./www-grimoire
        run: yarn test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
